# Numpy Module :
---
- NumPy (Numerical Python) is a popular Python library used for numerical and scientific computing.
- It provides a powerful object called ndarray (N-dimensional array) that allows fast operations on large datasets.
---
# Key features of NumPy
---

- Multidimensional arrays (faster and more efficient than Python lists)
- Mathematical & statistical functions
- Linear algebra support (matrix operations)
- Random number generation
- Integration with machine learning & data science libraries like Pandas, Matplotlib, Scikit-learn, TensorFlow

---
**Why use NumPy instead of normal lists?**
---
| Python List              | NumPy Array                                      |
| ------------------------ | ------------------------------------------------ |
| Slower                   | Very fast                                        |
| Takes more memory        | Uses less memory                                 |
| No vectorized operations | Supports vectorized operations (no loops needed) |


---

## 📥 How to Install NumPy
---
**1️⃣ Install using pip**

        pip install numpy
---

## 2️⃣ Install in Virtual Environment
---
        python -m venv myenv
        myenv\Scripts\activate   # For Windows
        source myenv/bin/activate # For Linux/Mac

        pip install numpy
---

## 3️⃣ Check Installation
---
        import numpy as np
        print(np.__version__)

---


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr * 2)


[2 4 6 8]


# Where is NumPy used?

- Data Science & Machine Learning
- Artificial Intelligence
- Deep Learning
- Image Processing
- Scientific Computing
- Mathematical Simulations

## 🎯 Why NumPy is Fast?
---

| Python List                 | NumPy Array                |
| --------------------------- | -------------------------- |
| Stores objects              | Stores typed elements      |
| Slow loops                  | Vectorized fast operations |
| More memory required        | Less memory                |
| No built-in math operations | Rich mathematical support  |

  

In [3]:

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)   # Vector + Vector operation


[5 7 9]


# 📚 Important Inbuilt Functions in NumPy
---
**Array Creation Functions**

| Function        | Description         | Example              |
| --------------- | ------------------- | -------------------- |
| `np.array()`    | Create array        | `np.array([1,2,3])`  |
| `np.zeros()`    | Array with zeros    | `np.zeros(5)`        |
| `np.ones()`     | Array with ones     | `np.ones((2,3))`     |
| `np.empty()`    | Empty array         | `np.empty(4)`        |
| `np.arange()`   | Range values        | `np.arange(1,10,2)`  |
| `np.linspace()` | Equal spaced values | `np.linspace(0,1,5)` |

---

**Mathematical Functions :**
---

| Function      | Purpose            |
| ------------- | ------------------ |
| `np.min()`    | Minimum value      |
| `np.max()`    | Maximum value      |
| `np.sum()`    | Sum of elements    |
| `np.mean()`   | Average value      |
| `np.median()` | Median             |
| `np.std()`    | Standard deviation |
| `np.sqrt()`   | Square root        |

---

**Random Functions :**
---

| Function              | Description         |
| --------------------- | ------------------- |
| `np.random.rand()`    | Random numbers      |
| `np.random.randint()` | Random integers     |
| `np.random.randn()`   | Normal distribution |

---

In [7]:
print(np.random.randint(1,100,5))
print("-"*50)
m = np.array([[1,2],[3,4]])
print(np.linalg.det(m))


[15 82 31 62 51]
--------------------------------------------------
-2.0000000000000004


In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))


15
3.0
5
1


# 📐 Matrix / Linear Algebra Functions :
---

| Function          | Description           |
| ----------------- | --------------------- |
| `np.dot()`        | Matrix multiplication |
| `np.transpose()`  | Transpose matrix      |
| `np.linalg.inv()` | Inverse of matrix     |
| `np.linalg.det()` | Determinant           |

---


In [5]:
m = np.array([[1,2],[3,4]])
print(np.linalg.det(m))


-2.0000000000000004


# 🧠 Reshaping and Manipulating Arrays :
---

| Function        | Meaning          |
| --------------- | ---------------- |
| `reshape()`     | Change shape     |
| `flatten()`     | Convert to 1D    |
| `concatenate()` | Join arrays      |
| `split()`       | Split into parts |

---

In [6]:
arr = np.array([[1,2],[3,4]])
print(arr.reshape(4))   # Convert 2x2 into 1x4


[1 2 3 4]


# 🌟 Conclusion
---
NumPy is a powerful library used mainly in:
- Data Science
- Machine Learning
- Deep Learning
- Image Processing
- Scientific research
- Mathematical operations

---